### ISSUE TITLE
Additional Lances: Variation AL lances based on player drop skulls/difficulty

### ISSUE THREAD

**Issue by CWolfs** [CWolfs/MissionControl#165]
Provide the ability to config AL to take the player's drop skull rating of their lance(s) into account when calculating how many AL lances they should spawn.

From Morph:
```
lanceRatingWidget.Difficulty
on LanceHeaderWidget

SGDifficultyIndicatorWidget lanceRatingWidget = (SGDifficultyIndicatorWidget)AccessTools.Field(typeof(LanceHeaderWidget), "lanceRatingWidget").GetValue(__instance);

if you grab that on drop button click
```

From Lady:
```
so when they bring a 2 skull to a 5 skull, mc will be a bit more lenient on them, if they bring a 5 skull into a 1 skull they still face nastys
```

**Comment by CWolfs** [comment]
I need to consider how I can intergrate this with the current MC calculation methods for AL without causing weirdness.

**Comment by LadyAlekto** [comment]
Ive wrote down some thoughts on this because i really want this (no pressuring, just giddy fangirl thinking of solutions ;) )

My suggestion would be to make the chance multiplier a float

Where as 1 (default) changes nothing, and settings defines how much the half skulls adds or removes from that float (if set true)

Eg 

EnemySpawnChanceLanceMultiplier 0.1 would add 0.1 to the float for each half skull fielded for enemy lances
AllySpawnChanceLanceMultiplier -0.1 would substract 0.1 to the float for each half skull fielded for Allys

A spawn chance of 0.5 for a enemy lance would be multiplied by 1.1 to 0.55

While a spawn chance for an allied lance would be modifiered to 0.45

So if the multiplier option would be present in settings it would adjust all missions dynamically

Setting no multipliers wouldnt change anything for anyone not using it

**Comment by CWolfs** [comment]
Sounds like a good suggestion. It'll be worth implementing this and seeing how it works out. Thanks @LadyAlekto

**Comment by CWolfs** [comment]
Settinged on the following `settings.json` config under the `AdditionalLances` section.

```json
    "DropWeightInfluence": {
      "Enable": false,
      "GlobalEnemyChanceToSpawn": 0.05,
      "GlobalAllyChanceToSpawn": 0.8,
      "EnemySpawnInfluencePerHalfSkull": 0.1,
      "AllySpawnInfluencePerHalfSkull": -0.1
    }
```

**Comment by LadyAlekto** [comment]
Additional lance global modifier

The basic idea is the ability to dynamically adjust contracts based on the relative power of a player themself

-tied to difference between contract difficulty and dropped lance rating
Eg a contract is 3 skulls (d6) and player drops a 2 skull lance (d4)

the would have a increase for ally spawns by 2 of the value
and a decrease of enemy spawn by 2 of the value

---------

-new idea, chance above 100 spawns additional lances
eg 120% chance spawns 1 additional lance, and a 20% chance for a second lance (ignoring the limits otherwise applied to maximum lances)

**Comment by CWolfs** [comment]
In `develop` for the contract difficulty influence.

I'll create a new feature request for changing/influencing the max lance amount.
