### ISSUE TITLE
enamy additional lance destruction gain too much (7500%) "Version": "0.4.6"

### ISSUE THREAD

**Issue by f-abel** [CWolfs/MissionControl#309]
well it's the second time i face this on my campaign.
Cool get a huge amount of $$$ but, a little overkill...
At the reward table objective 1 ok, objective 2 +10% ... and then additional lance 7500%
And I can't find from where it comes all ContractBonusRewardPct are =<0.3 in my mod directory.
Sounds like uninitialised value...

Note I run Linux.
Is there a place i can set a default ContractBonusRewardPct=0.15 for instance ?

thank you

**Comment by CWolfs** [comment]
Hey,

This is a known issue with MC and comma based decimal locales (e.g. Russian etc). Check #269.

This is fixed in MC 1.0 and will be released today or tomorrow.

Sadly there's no global area to set this reward value but you can edit it under `MissionControl/config/AdditionalLances/` .json files and adding the following JSON chunk in the top level of the file.

e.g.

```
"AdditionalLances": {
    // more configuration
    "RewardsPerLance": [
      {
        "Type": "ContractBonusRewardPct",
        "Value": "0,4",
      }
    ],
   // more configuration
}
```
