### ISSUE TITLE
Additional Lances: Runtime API to add new support lances

### ISSUE THREAD

**Issue by CWolfs** [CWolfs/MissionControl#513]
Provide a runtime API to add a new form of support lance, independent of the typical AdditionalLances lance setup. The calling mod would call this before MC processes the Additional Lances.

The API method should allow for, but not limited to:

* LanceOverride to be provided to be consumed by MC
* IsAPrimaryObjective
* Optional custom objective name (e.g. Destroy Light Lancers instead of Destroy Support Lance 4)

**Comment by CWolfs** [comment]
Questions that need answering:

* When AL overrides are set via the API - should it enforce AL even if the player's MC config has set AL to disabled? This includes
  * The main AL enable/disable
  * Contract type exclude list
  * AL weight restriction exemption list 
* Should AL overrides set via the API override all other AL settings (e.g. 'per-contract' AL contract / fp overrides)
  * These 'per-contract' overrides are used by modders to enforce specific AL for contracts or FPs

**Comment by BlueWinds** [comment]
IMO "override allied lance settings" should be toggleable - eg, WarTech IIC might want to say "whatever the default AL settings, I'm adding an additional lance on top of them (if there are any) to this mission" - or alternately, it should also be possible to say "I'm taking control of the additional lances in this mission, please ignore settings."

Basically - I think any allied lances created via API should ignore the settings file, and additionally the API should be able to toggle AL that would be generated by the settings off at runtime.

I mention WIIC, because I'm currently working on a massive expansion of its capabilities, in the direction of "Flashpoints 2.0," and overriding / adding lances to missions would make a lot of sense in that context. This API is something I'd definitely consider consuming (though I don't have concrete plans at the moment).

**Comment by wmtorode** [comment]
I would say yes or toggleable, this gives the calling mod the flexibility to override in some situations. In particular when players have AL off in RT, I may still wish to drop the extra lance on them. Mostly  I think what Blue has aligns with my thoughts on the matter

**Comment by CWolfs** [comment]
@BlueWinds @wmtorode  Seems sensible enough. I'm just concerned that this feature will be abused to the point where the MC Additional Lances are no longer used. I can see the point for RTO to 'sync' with the online play but with WarTech I'll be concerned it will just flat out override all of the MC AL system.

I'm also concerned that specific flashpoints are set up by designers/authors to have a very specific setup with the MC 'per-contract' overrides. In these cases I'm inclined to not allow this API to work on flashpoints as it would destroy the balance the flashpoint author has created. What do you guys think on that?

**Comment by BlueWinds** [comment]
Extended contracts can really be used in two ways: Either procedurally generating missions ("every three days, give the user a mission of difficulty 3), or as crafted flashpoint-like story experiences (on day 1, play this conversation. On day 2, drop this contract. On day 3, trigger this event which sets company flags, and on day 4, trigger one of two missions depending on what flags the company has).

I'd like to allow Extended Contract authors to configure AL directly in the same place they configure everything else about the Extended Contract, as much as possible rather than having it scattered across Extended Contract -> Contract -> MC configuration.

The more I can make it easy to understand and use, documented and written in one place, the more likely the community is to actually make cool ones! That's why I'd like the power to exist in the API, precisely because it sounds really neat for authoring flashpoint-like things. In some cases (procedural extended contracts), letting MC handle the details is great (maybe there's a final super-difficult mission where we drop two extra lances on the player, but the enemy could be any faction, and want the MC configuration to figure out what's correct), but in other cases more control would be great ("Let's launch contract XYZ, and ensure there are no allied lances because it's supposed to be a tutorial mission.")

**Comment by wmtorode** [comment]
@CWolfs I see your concern, I cant speak to Blue's mind too much, but for me my planned use is very sparingly and in regards to flashpoints, I have no opinion on that matter, RTO explicitly doesn't deal with flashpoints (as in flashpoints exist and spawn, but RTO doesnt allow them to be used for control changes and ignores them so that they remain purely as the authors intended)

**Comment by BlueWinds** [comment]
Yeah, WIIC is much the same - it ignores flashpoints (and 99% of all contracts, in fact), and is only concerned with missions generated through its own configuration.

**Comment by CWolfs** [comment]
Sounds good to me. Thanks for the feedback and extra information guys. I'll work on getting this in soon.

**Comment by CWolfs** [comment]
This has been implemented now and is used like in the examples below. **_Whenever you see a `MLanceOverride` you can substitude a normal `LanceOverride` for it if you prefer_**. The MLanceOverride provides you some extra functionality for MC's autofill behaviour and a helpful constructor.

**1 - You can choose to set only the AL count and let MC handle the rest**

```csharp
MissionControl.Instance.API.SetOverriddenAdditionalLances("allies", 5);
```

**2 - You can specify a LanceOverride (or MLanceOverride)

**2.1 - ...using a Tagged Lance**

```csharp
      // Example of using Tagged lance
      UnitSpawnPointOverride mech = new UnitSpawnPointOverride();
      mech.unitDefId = UnitSpawnPointOverride.UseLance;
      mech.pilotDefId = UnitSpawnPointOverride.UseLance;

      // Test overrides
      MLanceOverride m1 = new MLanceOverride("Tagged", new HBS.Collections.TagSet("lance_type_battle", "lance_type_assault"), new HBS.Collections.TagSet(), new HBS.Collections.TagSet(), 0, new List<UnitSpawnPointOverride>() {
        mech.DeepCopy(), // Uses MC's deep copy UnitSpawnPointOverride extension method to make a new unit spawn GUID on copy
        mech.DeepCopy(), // Uses MC's deep copy UnitSpawnPointOverride extension method to make a new unit spawn GUID on copy
        mech.DeepCopy(), // Uses MC's deep copy UnitSpawnPointOverride extension method to make a new unit spawn GUID on copy
        mech.DeepCopy(), // Uses MC's deep copy UnitSpawnPointOverride extension method to make a new unit spawn GUID on copy
      });
```

2.2 - ... using a specific LanceDef

```csharp
      // Example of using specified LanceDef
      MLanceOverride m2 = new MLanceOverride("lancedef_arena_medium_recon", new HBS.Collections.TagSet(), new HBS.Collections.TagSet(), new HBS.Collections.TagSet(), 0, new List<UnitSpawnPointOverride>() {
        mech.DeepCopy(), // Uses MC's deep copy UnitSpawnPointOverride extension method to make a new unit spawn GUID on copy
        mech.DeepCopy(), // Uses MC's deep copy UnitSpawnPointOverride extension method to make a new unit spawn GUID on copy 
        mech.DeepCopy(), // Uses MC's deep copy UnitSpawnPointOverride extension method to make a new unit spawn GUID on copy
        mech.DeepCopy(), // Uses MC's deep copy UnitSpawnPointOverride extension method to make a new unit spawn GUID on copy
      });
```

2.3 - ... using a Manual lance override

```csharp
      // Example of using Manual lance

      // Unit 1
      UnitSpawnPointOverride manualLanceUnit1 = new UnitSpawnPointOverride();
      manualLanceUnit1.unitType = UnitType.Mech;
      manualLanceUnit1.unitDefId = "mechdef_awesome_AWS-8T";
      manualLanceUnit1.pilotDefId = "pilot_d7_pilot";

      // Unit 2
      UnitSpawnPointOverride manualLanceUnit2 = new UnitSpawnPointOverride();
      manualLanceUnit2.unitType = UnitType.Mech;
      manualLanceUnit2.unitDefId = "mechdef_battlemaster_BLR-1GB";
      manualLanceUnit2.pilotDefId = "pilot_d5_pilot";

      // Unit 3
      UnitSpawnPointOverride manualLanceUnit3 = new UnitSpawnPointOverride();
      manualLanceUnit3.unitType = UnitType.Vehicle;
      manualLanceUnit3.unitDefId = "vehicledef_SWIFTWIND";
      manualLanceUnit3.pilotDefId = "pilot_d3_pilot";

      // Unit 4
      UnitSpawnPointOverride manualLanceUnit4 = new UnitSpawnPointOverride();
      manualLanceUnit4.unitType = UnitType.Vehicle;
      manualLanceUnit4.unitDefId = "vehicledef_DEMOLISHER";
      manualLanceUnit4.pilotDefId = "pilot_d9_pilot";

      MLanceOverride m3 = new MLanceOverride("Manual", new HBS.Collections.TagSet(), new HBS.Collections.TagSet(), new HBS.Collections.TagSet(), 0, new List<UnitSpawnPointOverride>() {
        manualLanceUnit1,
        manualLanceUnit2,
        manualLanceUnit3,
        manualLanceUnit4,
      });
```

2.4 - Then you send it to Mission Control with the MLanceOveride API method or the LanceOverride API method.

```csharp
      MissionControl.Instance.API.SetOverriddenAdditionalLances("allies", new List<MLanceOverride>() {
        new MLanceOverride(m1),
        new MLanceOverride(m2),
        new MLanceOverride(m3)
      });
```

OR

```csharp
MissionControl.Instance.API.SetOverriddenAdditionalLances("allies", new List<LanceOverride>() { (LanceOverride)m1, (LanceOverride)m2, lanceOverride3 });
```

**Comment by CWolfs** [comment]
@wmtorode @BlueWinds Here's how this will be used. I've implemented it in a branch at the moment and just testing it. Looks good so far. You can set the API method before MC starts to build things and it will reset when Mission Control has finished building everything (so it'll be used only for one 'build').

**Comment by CWolfs** [comment]
In `develop`.

**Comment by CWolfs** [comment]
You can also provide a list of objective names to override the generated ones for enemy AL.

```jsonc
MissionControl.Instance.API.SetOverriddenAdditionalLances("allies", lanceOverrides, new List<string>() { 
    "Destroy the traitors",  // Used instead of 'Destroy {faction} Support Lance 1'
    "Destroy the damaged reinforcements" // Used instead of 'Destroy {faction} Support Lance 2'
});
```
